### ISSUE TITLE
Can Not Resolve Symbol LibOpenConnect in Android Studio. 

### ISSUE THREAD

**Issue by Taimoor-AbdULLAH** [cernekee/openconnect#2]
Hi cernekee!,Will you please help me out about This Liberary Issue. how to add this library in android studio. and Also  its giving error in this import..... "import org.infradead.libopenconnect.LibOpenConnect" can not resolve symbol infradead....

**Comment by francescovigot** [comment]
I have the same problem if you have found its solution please tell me

**Comment by cernekee** [comment]
Hi, I think you probably want to file bugs against https://github.com/cernekee/ics-openconnect/

This project is just my local copy of the upstream (non-Android) openconnect tree.  It is the underlying library.

In the ics-openconnect project I recently added a download-artifacts.sh script which fetches the JAR files and native libraries from a recent Travis CI build.  This lets you build the app using Android Studio without setting up NDK and building the native components.  Take a look at the README for instructions.
